spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expenses-tracker
    username: postgres
    password: Avocado100.

  jpa:
    hibernate:
      ddl-auto: create-drop

  security:
    user:
      password: user


jwt:
  jwtSecret: secretKey
  jwtExpirationMs: 1000000000